#Add the controller params. Create a launch file to start controllers separately
mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_hinge
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_hinge
    pid: { p: 100.0, i: 0.01, d: 10.0 }
  # Position Controllers ---------------------------------------
#  joint1_position_controller:
#    type: position_controllers/JointPositionController
#    joint: left_wheel_hinge
#    pid: {p: 100.0, i: 0.01, d: 10.0}
#  joint2_position_controller:
#    type: position_controllers/JointPositionController
#    joint: right_wheel_hinge
#    pid: {p: 100.0, i: 0.01, d: 10.0}


