<?xml version='1.0'?>
<robot name="mybot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Put here the robot properties common to the model -->
	<xacro:include filename="$(find mybot_description)/urdf/mybot.gazebo" />
	<xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find mybot_description)/urdf/macros.xacro" />

	<xacro:property name="PI" value="3.1415926535897931"/>

	<xacro:property name="chassisHeight" value="0.1"/>
	<xacro:property name="chassisLength" value="0.4"/>
	<xacro:property name="chassisWidth" value="0.2"/>
	<xacro:property name="chassisMass" value="50.0"/>

	<xacro:property name="casterRadius" value="0.1"/>
	<xacro:property name="casterMass" value="5.0"/>

	<xacro:property name="wheelWidth" value="0.05"/>
	<xacro:property name="wheelRadius" value="0.1"/>
	<xacro:property name="wheelPos" value="0.2"/>
	<xacro:property name="wheelMass" value="5.0"/>

	<xacro:property name="cameraSize" value="0.05"/>
	<xacro:property name="cameraMass" value="0.1"/>
	<!-- End of common prperties description -->

<!--	<link name="footprint">-->
<!--	<inertial>-->
<!--		<mass value="0.0"/>-->
<!--		<inertia name="baseFrameInertia">-->
<!--			ixx="1.0" ixy="0.0" ixz="0.0"-->
<!--			iyy="0.0" iyz="0.0"-->
<!--			izz="0.0"/>-->
<!--		</inertia>-->
<!--	</inertial>-->
<!--	</link>-->

<!--	<joint name="base_joint" type="fixed">-->
<!--		<parent link="footprint"/>-->
<!--		<child link="chassis"/>-->
<!--	</joint>-->


	<link name='chassis'>
		<pose>0 0 0.1 0 0 0</pose>
<!--		Box of chassis properties-->
		<collision name="chassisCollision">
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
			<geometry>
				<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
			<geometry>
				<box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<inertial name="chassisInertia">
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
			<mass value="${chassisMass}"/>
			<xacro:box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
		</inertial>
	</link>

	<joint name="fixed" type="fixed">
		<parent link="chassis"/>
		<child link="caster_wheel"/>
	</joint>

	<link name="caster_wheel">
		<collision>
			<origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
			<geometry>
				<sphere radius="${casterRadius}"/>
			</geometry>
		</collision>

		<visual>
			<origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
			<geometry>
				<sphere radius="${casterRadius}"/>
			</geometry>
			<material name="red"/>
		</visual>

		<inertial>
			<origin xyz="${casterRadius-chassisLength/2} 0 ${casterRadius-chassisHeight+wheelRadius}" rpy="0 0 0"/>
			<mass value="${casterMass}"/>
			<xacro:sphere_inertia m="${casterMass}" r="${casterRadius}"/>
		</inertial>
	</link>

<!--Macros for wheels: Links and Joints both-->
	<xacro:wheel lr="left" tY="1"/>
	<xacro:wheel lr="right" tY="-1"/>

</robot>